# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- development

pool:
  vmImage: 'windows-2019'

variables:
- group: CI-Variables

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Install-Module AzureAD -Force
      Import-Module AzureAD
      $Username = '$(Username)'
      $Password = '$(Password)' | ConvertTo-SecureString -asPlainText -Force
      $Credential = New-Object System.Management.Automation.PSCredential($Username,$Password)
      Connect-AzureAD -Credential $Credential
      Get-AzureADUser