# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- development

pool:
  vmImage: 'windows-2019'

variables:
- group: CI-Variables

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $WorkingDirectory = $($PWD)
      Install-Module dxExchange.Online -Force
      $Username = '$(Username)'
      $Password = '$(Password)' | ConvertTo-SecureString -AsPlainText -Force
      $ExoCredential = New-Object System.Management.Automation.PSCredential($Username,$Password)
      Import-Module dxExchange.Online
      cd $WorkingDirectory
      .\Exchange\OrganizationConfig.Remediation.ps1 -All -Verbose
      Invoke-Pester
      Get-PSSession | Remove-PSSession