# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- development

pool:
  vmImage: 'windows-2019'

variables:
- group: CI-Variables

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $PWD
      Install-Module dxExchange.Online -Force
      $Username = '$(Username)'
      $Password = '$(Password)' | ConvertTo-SecureString -AsPlainText -Force
      $ExoCredential = New-Object System.Management.Automation.PSCredential($Username,$Password)
      Import-Module dxExchange.Online
      $PWD
      D:\a\1\s\Exchange\OrganizationConfig.Remediation.ps1
      Invoke-Pester
      Get-PSSession | Remove-PSSession